/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    DataInputStage: typeof import('./components/DataInputStage.vue')['default']
    DefineClass: typeof import('./components/DefineClass.vue')['default']
    DefineClasses: typeof import('./components/DefineClasses.vue')['default']
    DefineIndex: typeof import('./components/DefineIndex.vue')['default']
    DefineIndexSet: typeof import('./components/DefineIndexSet.vue')['default']
    DefineTecEnum: typeof import('./components/DefineTecEnum.vue')['default']
    DefineTecEnums: typeof import('./components/DefineTecEnums.vue')['default']
    DefineTecSchema: typeof import('./components/DefineTecSchema.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InputClass: typeof import('./components/InputClass.vue')['default']
    InputParam: typeof import('./components/InputParam.vue')['default']
    InputRecurse: typeof import('./components/InputRecurse.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaStage: typeof import('./components/SchemaStage.vue')['default']
  }
}
