/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    GridView: typeof import('./components/GridView.vue')['default']
    GridView1D: typeof import('./components/GridView1D.vue')['default']
    GridView2D: typeof import('./components/GridView2D.vue')['default']
    GridView3D: typeof import('./components/GridView3D.vue')['default']
    InputParam: typeof import('./components/InputParam.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectAttributeType: typeof import('./components/SelectAttributeType.vue')['default']
    SelectIndexType: typeof import('./components/SelectIndexType.vue')['default']
    StageClass: typeof import('./components/StageClass.vue')['default']
    StageEnum: typeof import('./components/StageEnum.vue')['default']
    StageGraph: typeof import('./components/StageGraph.vue')['default']
    StageInput: typeof import('./components/StageInput.vue')['default']
    StagePnum: typeof import('./components/StagePnum.vue')['default']
    StageSql: typeof import('./components/StageSql.vue')['default']
    TecClass: typeof import('./components/TecClass.vue')['default']
    TecClassAST: typeof import('./components/TecClassAST.vue')['default']
    TecEnum: typeof import('./components/TecEnum.vue')['default']
    TecEnumAST: typeof import('./components/TecEnumAST.vue')['default']
    TecMatch: typeof import('./components/TecMatch.vue')['default']
    TecNode: typeof import('./components/TecNode.vue')['default']
    TecNodeAST: typeof import('./components/TecNodeAST.vue')['default']
    TecNodeIndex: typeof import('./components/TecNodeIndex.vue')['default']
    TecNodeNullable: typeof import('./components/TecNodeNullable.vue')['default']
    TecNodeSet: typeof import('./components/TecNodeSet.vue')['default']
    TecPnum: typeof import('./components/TecPnum.vue')['default']
    TecPnumAst: typeof import('./components/TecPnumAst.vue')['default']
    TecPnumTable: typeof import('./components/TecPnumTable.vue')['default']
    TecSignature: typeof import('./components/TecSignature.vue')['default']
  }
}
