/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Code: typeof import('./components/Code.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HStack: typeof import('./components/HStack.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    Name: typeof import('./components/Name.vue')['default']
    PageNumber: typeof import('./components/PageNumber.vue')['default']
    Query: typeof import('./components/Query.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TecAST: typeof import('./components/TecAST.vue')['default']
    Text: typeof import('./components/Text.vue')['default']
    VStack: typeof import('./components/VStack.vue')['default']
  }
}
