/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Code: typeof import('./components/Code.vue')['default']
    EntryMatrix: typeof import('./components/EntryMatrix.vue')['default']
    Fabrics: typeof import('./components/Fabrics.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HStack: typeof import('./components/HStack.vue')['default']
    Image: typeof import('./components/Image.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    Many: typeof import('./components/Many.vue')['default']
    Name: typeof import('./components/Name.vue')['default']
    PageNumber: typeof import('./components/PageNumber.vue')['default']
    Pantone: typeof import('./components/Pantone.vue')['default']
    Pattern: typeof import('./components/Pattern.vue')['default']
    Pom: typeof import('./components/Pom.vue')['default']
    Query: typeof import('./components/Query.vue')['default']
    Render: typeof import('./components/Render.vue')['default']
    Resizable: typeof import('./components/Resizable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectTecType: typeof import('./components/SelectTecType.vue')['default']
    Single: typeof import('./components/Single.vue')['default']
    Stack: typeof import('./components/Stack.vue')['default']
    StrictTable: typeof import('./components/StrictTable.vue')['default']
    TecAST: typeof import('./components/TecAST.vue')['default']
    TecBinding: typeof import('./components/TecBinding.vue')['default']
    TecLang: typeof import('./components/TecLang.vue')['default']
    TecType: typeof import('./components/TecType.vue')['default']
    Text: typeof import('./components/Text.vue')['default']
    VStack: typeof import('./components/VStack.vue')['default']
    Zip: typeof import('./components/Zip.vue')['default']
  }
}
